<option value="Afeganistão"><?php pten('Afeganistão','Afghanistan');?></option>
						<option value="África do Sul"><?php pten('África do Sul','South Africa');?></option>
						<option value="Albânia"><?php pten('Albânia','Albania');?></option>
						<option value="Alemanha"><?php pten('Alemanha','Germany');?></option>
						<option value="Andorra"><?php pten('Andorra','Andorra');?></option>
						<option value="Angola"><?php pten('Angola','Angola');?></option>
						<option value="Anguilla"><?php pten('Anguilla','Anguilla');?></option>
						<option value="Antártida"><?php pten('Antártida','Antarctica');?></option>
						<option value="Antígua e Barbuda"><?php pten('Antígua e Barbuda','Antigua and Barbuda');?></option>
						<option value="Antilhas Holandesas"><?php pten('Antilhas Holandesas','Netherlands Antilles');?></option>
						<option value="Arábia Saudita"><?php pten('Arábia Saudita','Saudi Arabia');?></option>
						<option value="Argélia"><?php pten('Argélia','Algeria');?></option>
						<option value="Argentina"><?php pten('Argentina','Argentina');?></option>
						<option value="Armênia"><?php pten('Arménia','Armenia');?></option>
						<option value="Aruba"><?php pten('Aruba','');?></option>
						<option value="Austrália"><?php pten('Austrália','Australia');?></option>
						<option value="Áustria"><?php pten('Áustria','Austria');?></option>
						<option value="Azerbaijão"><?php pten('Azerbaijão','Azerbaijan');?></option>
						<option value="Bahamas"><?php pten('Bahamas','');?></option>
						<option value="Bangladesh"><?php pten('Bangladeche','Bangladesh');?></option>
						<option value="Barbados"><?php pten('Barbados','');?></option>
						<option value="Barein"><?php pten('Barém','Bahrain');?></option>
						<option value="Bélgica"><?php pten('Bélgica','Belgium');?></option>
						<option value="Belize"><?php pten('Belize','');?></option>
						<option value="Benin"><?php pten('Benim','Benin');?></option>
						<option value="Bermudas"><?php pten('Bermudas','');?></option>
						<option value="Bielo-Rússia"><?php pten('Bielorrússia','Belarus');?></option>
						<option value="Bolívia"><?php pten('Bolívia','Bolivia');?></option>
						<option value="Bósnia-Herzegovina"><?php pten('Bósnia e Herzegovina','Bosnia and Herzegovina');?></option>
						<option value="Botsuana"><?php pten('Botswana','');?></option>
						<option value="Brasil"><?php pten('Brasil','Brazil');?></option>
						<option value="Brunei Darussalam"><?php pten('Brunei','');?></option>
						<option value="Bulgária"><?php pten('Bulgária','Bulgaria');?></option>
						<option value="Burkina Fasso"><?php pten('Burkina Faso','');?></option>
						<option value="Burundi"><?php pten('Burundi','');?></option>
						<option value="Butão"><?php pten('Butão','Bhutan');?></option>
						<option value="Cabo Verde"><?php pten('Cabo Verde','');?></option>
						<option value="Camarões"><?php pten('Camarões','Cameroon');?></option>
						<option value="Camboja"><?php pten('Camboja','Cambodia');?></option>
						<option value="Canadá"><?php pten('Canadá','Canada');?></option>
						<option value="Cayman, Ilhas"><?php pten('Cayman, Ilhas','Cayman Islands');?></option>
						<option value="Cazaquistão"><?php pten('Cazaquistão','Kazakhstan');?></option>
						<option value="Chade"><?php pten('Chade','');?></option>
						<option value="Chile"><?php pten('Chile','');?></option>
						<option value="China"><?php pten('China','');?></option>
						<option value="Chipre"><?php pten('Chipre','Cyprus');?></option>
						<option value="Colômbia"><?php pten('Colômbia','Colômbia');?></option>
						<option value="Ilhas Comores"><?php pten('Comores','Comoros');?></option>
						<option value="Congo"><?php pten('Congo','');?></option>
						<option value="Coréia do Norte"><?php pten('Coreia do Norte','North Korea');?></option>
						<option value="Coréia do Sul"><?php pten('Coreia do Sul','South Korea');?></option>
						<option value="Costa do Marfim"><?php pten('Costa do Marfim','Ivory Coast');?></option>
						<option value="Costa Rica"><?php pten('Costa Rica','');?></option>
						<option value="Croácia"><?php pten('Croácia','Croatia');?></option>
						<option value="Cuba"><?php pten('Cuba','');?></option>
						<option value="Dinamarca"><?php pten('Dinamarca','Denmark');?></option>
						<option value="Djibuti"><?php pten('Djibuti','');?></option>
						<option value="Dominica"><?php pten('Domínica','Dominica');?></option>
						<option value="Egito"><?php pten('Egipto','Egypt');?></option>
						<option value="El Salvador"><?php pten('El Salvador','');?></option>
						<option value="Emirados Árabes Unidos"><?php pten('Emirados Árabes Unidos','United Arab Emirates');?></option>
						<option value="Equador"><?php pten('Equador','Ecuador');?></option>
						<option value="Eritréia"><?php pten('Eritreia','Eritrea');?></option>
						<option value="Eslováquia"><?php pten('Eslováquia','Slovakia');?></option>
						<option value="Eslovênia"><?php pten('Eslovénia','Slovenia');?></option>
						<option value="Espanha"><?php pten('Espanha','Spain');?></option>
						<option value="Estados Unidos"><?php pten('Estados Unidos','USA');?></option>
						<option value="Estônia"><?php pten('Estónia','Estonia');?></option>
						<option value="Etiópia"><?php pten('Etiópia','Ethiopia');?></option>
						<option value="Fiji"><?php pten('Fiji','');?></option>
						<option value="Filipinas"><?php pten('Filipinas','Philippines');?></option>
						<option value="Finlândia"><?php pten('Finlândia','');?></option>
						<option value="França"><?php pten('França','');?></option>
						<option value="Gabão"><?php pten('Gabão','');?></option>
						<option value="Gâmbia"><?php pten('Gâmbia','');?></option>
						<option value="Gana"><?php pten('Gana','');?></option>
						<option value="Geórgia"><?php pten('Geórgia','');?></option>
						<option value="Gibraltar"><?php pten('Gibraltar','');?></option>
						<option value="Granada"><?php pten('Granada','');?></option>
						<option value="Grécia"><?php pten('Grécia','');?></option>
						<option value="Groenlândia"><?php pten('Groenlândia','');?></option>
						<option value="Guadalupe"><?php pten('Guadalupe','');?></option>
						<option value="Guam"><?php pten('Guam','');?></option>
						<option value="Guatemala"><?php pten('Guatemala','');?></option>
						<option value="Guernsey"><?php pten('Guernsey','');?></option>
						<option value="Guiana"><?php pten('Guiana','');?></option>
						<option value="Guiana Francesa"><?php pten('Guiana Francesa','');?></option>
						<option value="Guiné"><?php pten('Guiné','');?></option>
						<option value="Guiné Equatorial"><?php pten('Guiné Equatorial','');?></option>
						<option value="Guiné-Bissau"><?php pten('Guiné-Bissau','');?></option>
						<option value="Haiti"><?php pten('Haiti','');?></option>
						<option value="Honduras"><?php pten('Honduras','');?></option>
						<option value="Hong Kong"><?php pten('Hong Kong','');?></option>
						<option value="Hungria"><?php pten('Hungria','');?></option>
						<option value="Iêmen"><?php pten('Iémen','');?></option>
						<option value="Ilha Bouvet"><?php pten('Ilha Bouvet','');?></option>
						<option value="Ilha de Man"><?php pten('Ilha de Man','');?></option>
						<option value="Ilha Christmas"><?php pten('Ilha do Natal','');?></option>
						<option value="Ilha Norfolk"><?php pten('Ilha Norfolk','');?></option>
						<option value="Ilhas Åland"><?php pten('Ilhas Åland','');?></option>
						<option value="Ilhas Cocos (Keeling)"><?php pten('Ilhas Cocos (Keeling)','');?></option>
						<option value="Ilhas Cook"><?php pten('Ilhas Cook','');?></option>
						<option value="Ilhas Feroé"><?php pten('Ilhas Feroé','');?></option>
						<option value="Geórgia do Sul e Ilhas Sandwich do Sul"><?php pten('Ilhas Geórgia do Sul e Sandwich do Sul','');?></option>
						<option value="Ilhas Heard e McDonald"><?php pten('Ilhas Heard e Ilhas McDonald','');?></option>
						<option value="Ilhas Malvinas (Falkland)"><?php pten('Ilhas Malvinas (Falkland)','');?></option>
						<option value="Ilhas Marianas do Norte"><?php pten('Ilhas Marianas do Norte','');?></option>
						<option value="Ilhas Marshall"><?php pten('Ilhas Marshall','');?></option>
						<option value="Territórios Insulares dos Estados Unidos"><?php pten('Ilhas Menores Distantes dos Estados Unidos','');?></option>
						<option value="Ilhas Salomão"><?php pten('Ilhas Salomão','');?></option>
						<option value="Ilhas Virgens Americanas"><?php pten('Ilhas Virgens Americanas','');?></option>
						<option value="Ilhas Virgens Britânicas"><?php pten('Ilhas Virgens Britânicas','');?></option>
						<option value="Ilhas Wallis e Futuna"><?php pten('Ilhas Wallis e Futuna','');?></option>
						<option value="Índia"><?php pten('Índia','');?></option>
						<option value="Indonésia"><?php pten('Indonésia','');?></option>
						<option value="Irã"><?php pten('Irão','');?></option>
						<option value="Iraque"><?php pten('Iraque','');?></option>
						<option value="Irlanda"><?php pten('Irlanda','');?></option>
						<option value="Islândia"><?php pten('Islândia','');?></option>
						<option value="Israel"><?php pten('Israel','');?></option>
						<option value="Itália"><?php pten('Itália','');?></option>
						<option value="Jamaica"><?php pten('Jamaica','');?></option>
						<option value="Japão"><?php pten('Japão','');?></option>
						<option value="Jersey"><?php pten('Jersey','');?></option>
						<option value="Jordânia"><?php pten('Jordânia','');?></option>
						<option value="Kuwait"><?php pten('Kuwait','');?></option>
						<option value="Lesoto"><?php pten('Lesoto','');?></option>
						<option value="Letônia"><?php pten('Letónia','');?></option>
						<option value="Líbano"><?php pten('Líbano','');?></option>
						<option value="Libéria"><?php pten('Libéria','');?></option>
						<option value="Líbia"><?php pten('Líbia','');?></option>
						<option value="Liechtenstein"><?php pten('Listenstaine','');?></option>
						<option value="Lituânia"><?php pten('Lituânia','');?></option>
						<option value="Luxemburgo"><?php pten('Luxemburgo','');?></option>
						<option value="Macau"><?php pten('Macau','');?></option>
						<option value="Macedônia"><?php pten('Macedónia','');?></option>
						<option value="Madagascar"><?php pten('Madagáscar','');?></option>
						<option value="Malta"><?php pten('Malásia','');?></option>
						<option value="Malásia"><?php pten('Malávi','');?></option>
						<option value="Malauí"><?php pten('Maldivas','');?></option>
						<option value="Maldivas"><?php pten('Mali','');?></option>
						<option value="Mali"><?php pten('Malta','');?></option>
						<option value="Marrocos"><?php pten('Marrocos','');?></option>
						<option value="Martinica"><?php pten('Martinica','');?></option>
						<option value="Ilhas Maurício"><?php pten('Maurícia','');?></option>
						<option value="Mauritânia"><?php pten('Mauritânia','');?></option>
						<option value="Mayotte"><?php pten('Mayotte','');?></option>
						<option value="México"><?php pten('México','');?></option>
						<option value="Micronésia"><?php pten('Micronésia','');?></option>
						<option value="Moçambique"><?php pten('Moçambique','');?></option>
						<option value="Moldávia"><?php pten('Moldávia','');?></option>
						<option value="Mônaco"><?php pten('Mónaco','');?></option>
						<option value="Mongólia"><?php pten('Mongólia','');?></option>
						<option value="Montenegro"><?php pten('Montenegro','');?></option>
						<option value="Montserrat"><?php pten('Montserrat','');?></option>
						<option value="Myanmar (antiga Birmânia)"><?php pten('Myanmar (antiga Birmânia)','');?></option>
						<option value="Namíbia"><?php pten('Namíbia','');?></option>
						<option value="Nauru"><?php pten('Nauru','');?></option>
						<option value="Nepal"><?php pten('Nepal','');?></option>
						<option value="Nicarágua"><?php pten('Nicarágua','');?></option>
						<option value="Níger"><?php pten('Níger','');?></option>
						<option value="Nigéria"><?php pten('Nigéria','');?></option>
						<option value="Niue"><?php pten('Niue','');?></option>
						<option value="Noruega"><?php pten('Noruega','');?></option>
						<option value="Nova Caledônia"><?php pten('Nova Caledónia','');?></option>
						<option value="Nova Zelândia"><?php pten('Nova Zelândia','');?></option>
						<option value="Omã"><?php pten('Omã','');?></option>
						<option value="Holanda"><?php pten('Países Baixos','');?></option>
						<option value="Palau"><?php pten('Palau','');?></option>
						<option value="Palestina"><?php pten('Palestina','');?></option>
						<option value="Panamá"><?php pten('Panamá','');?></option>
						<option value="Papua-Nova Guiné"><?php pten('Papua-Nova Guiné','');?></option>
						<option value="Paquistão"><?php pten('Paquistão','');?></option>
						<option value="Paraguai"><?php pten('Paraguai','');?></option>
						<option value="Peru"><?php pten('Peru','');?></option>
						<option value="Pitcairn"><?php pten('Pitcairn','');?></option>
						<option value="Polinésia Francesa"><?php pten('Polinésia Francesa','');?></option>
						<option value="Polônia"><?php pten('Polónia','');?></option>
						<option value="Porto Rico"><?php pten('Porto Rico','');?></option>
						<option value="Portugal"><?php pten('Portugal','');?></option>
						<option value="Catar"><?php pten('Qatar','');?></option>
						<option value="Quênia"><?php pten('Quénia','');?></option>
						<option value="Quirguistão"><?php pten('Quirguizistão','');?></option>
						<option value="Kiribati"><?php pten('Quiribati','');?></option>
						<option value="Reino Unido"><?php pten('Reino Unido','');?></option>
						<option value="República Centro-Africana"><?php pten('República Centro-Africana','');?></option>
						<option value="República Tcheca"><?php pten('República Checa','');?></option>
						<option value="República Democrática Popular do Laos"><?php pten('República Democrática Popular do Laos','');?></option>
						<option value="República Dominicana"><?php pten('República Dominicana','');?></option>
						<option value="Reunião"><?php pten('Reunião','');?></option>
						<option value="Romênia"><?php pten('Roménia','');?></option>
						<option value="Ruanda"><?php pten('Ruanda','');?></option>
						<option value="Russia"><?php pten('Rússia','Russia');?></option>
						<option value="Saara Ocidental"><?php pten('Saara Ocidental','');?></option>
						<option value="Samoa"><?php pten('Samoa','');?></option>
						<option value="Samoa Americana"><?php pten('Samoa Americana','');?></option>
						<option value="Santa Helena"><?php pten('Santa Helena','');?></option>
						<option value="Santa Lúcia"><?php pten('Santa Lúcia','');?></option>
						<option value="São Bartolomeu"><?php pten('São Bartolomeu','');?></option>
						<option value="São Cristóvão e Névis"><?php pten('São Cristóvão e Neves','');?></option>
						<option value="San Marino"><?php pten('São Marino','');?></option>
						<option value="São Martinho"><?php pten('São Martinho','');?></option>
						<option value="St. Pierre e Miquelon"><?php pten('São Pedro e Miquelon','');?></option>
						<option value="São Tomé e Príncipe"><?php pten('São Tomé e Príncipe','');?></option>
						<option value="São Vincente e Granadinas"><?php pten('São Vicente e Granadinas','');?></option>
						<option value="Ilhas Seychelles"><?php pten('Seicheles','');?></option>
						<option value="Senegal"><?php pten('Senegal','');?></option>
						<option value="Serra Leoa"><?php pten('Serra Leoa','');?></option>
						<option value="Sérvia"><?php pten('Sérvia','');?></option>
						<option value="Cingapura"><?php pten('Singapura','');?></option>
						<option value="Síria"><?php pten('Síria','');?></option>
						<option value="Somália"><?php pten('Somália','');?></option>
						<option value="Sri Lanka"><?php pten('Sri Lanca','');?></option>
						<option value="Suazilândia"><?php pten('Suazilândia','');?></option>
						<option value="Sudão"><?php pten('Sudão','');?></option>
						<option value="Sudão do Sul"><?php pten('Sudão do Sul','');?></option>
						<option value="Suécia"><?php pten('Suécia','');?></option>
						<option value="Suíça"><?php pten('Suíça','');?></option>
						<option value="Suriname"><?php pten('Suriname','');?></option>
						<option value="Svalbard e Jan Mayen"><?php pten('Svalbard e Jan Mayen','');?></option>
						<option value="Tailândia"><?php pten('Tailândia','');?></option>
						<option value="Taiwan"><?php pten('Taiwan','');?></option>
						<option value="Tajiquistão"><?php pten('Tajiquistão','');?></option>
						<option value="Tanzânia"><?php pten('Tanzânia','');?></option>
						<option value="Território Britânico do Oceano Índico"><?php pten('Território Britânico do Oceano Índico','');?></option>
						<option value="Territórios Franceses do Sul"><?php pten('Territórios Franceses do Sul','');?></option>
						<option value="Timor Leste"><?php pten('Timor-Leste','');?></option>
						<option value="Togo"><?php pten('Togo','');?></option>
						<option value="Toquelau"><?php pten('Tokelau','');?></option>
						<option value="Tonga"><?php pten('Tonga','');?></option>
						<option value="Trinidad e Tobago"><?php pten('Trindade e Tobago','');?></option>
						<option value="Tunísia"><?php pten('Tunísia','');?></option>
						<option value="Turcomenistão"><?php pten('Turcomenistão','');?></option>
						<option value="Turks e Caicos"><?php pten('Turks e Caicos','');?></option>
						<option value="Turquia"><?php pten('Turquia','');?></option>
						<option value="Tuvalu"><?php pten('Tuvalu','');?></option>
						<option value="Ucrânia"><?php pten('Ucrânia','');?></option>
						<option value="Uganda"><?php pten('Uganda','');?></option>
						<option value="Uruguai"><?php pten('Uruguai','');?></option>
						<option value="Uzbequistão"><?php pten('Uzbequistão','');?></option>
						<option value="Vanuatu"><?php pten('Vanuatu','');?></option>
						<option value="Vaticano"><?php pten('Vaticano','');?></option>
						<option value="Venezuela"><?php pten('Venezuela','');?></option>
						<option value="Vietnã"><?php pten('Vietname','');?></option>
						<option value="Zâmbia"><?php pten('Zâmbia','');?></option>
						<option value="Zimbábue"><?php pten('Zimbabué','');?></option>